version: "3.9"

services:
  db:
    image: postgres:17
    container_name: cloud_task_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pawnstar2004
      POSTGRES_DB: cloud_task
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: cloud_task_backend
    restart: always
    depends_on:
      - db
    environment:
      POSTGRES_USER: cloud_user
      POSTGRES_PASSWORD: cloud_pass
      POSTGRES_DB: cloud_task_db
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    ports:
      - "5000:5000"
    command: ["sh", "wait-for-db.sh", "db", "python", "app.py"]

  frontend:
    build:
      context: ./frontend
    container_name: cloud_task_frontend
    restart: always
    ports:
      - "3001:80"

volumes:
  db_data:
